In [1]:
# libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# data
df_orders = pd.read_csv('../data/raw/orders.csv')
df_products = pd.read_csv('../data/raw/products.csv')
df_aisles = pd.read_csv('../data/raw/aisles.csv')
df_departments = pd.read_csv('../data/raw/departments.csv')
df_order_products_prior = pd.read_csv('../data/raw/order_products__prior.csv')
df_order_products_train = pd.read_csv('../data/raw/order_products__train.csv')

In [3]:
# inspect
print(df_order_products_train.head())
# df_orders.head()
# df_products.head()
# df_aisles.head()
# df_departments.head()

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

## Merge and join dfs

In [4]:
# get sizes of dfs
print(df_order_products_prior.shape)
print(df_order_products_train.shape)

(32434489, 4)
(1384617, 4)

In [5]:
# Merge
df_merged = pd.concat([df_order_products_prior, df_order_products_train], ignore_index=True)
df_merged.tail()

          order_id  product_id  add_to_cart_order  reordered
33819101   3421063       14233                  3          1
33819102   3421063       35548                  4          1
33819103   3421070       35951                  1          1
33819104   3421070       16953                  2          1
33819105   3421070        4724                  3          1

In [6]:
# check everything was preserved
df_merged.shape

(33819106, 4)

In [7]:
df_merged = (
    df_merged
        .merge(df_orders, how="left", on="order_id")
        .merge(df_products, how="left", on="product_id")
        .merge(df_aisles, how="left", on="aisle_id")
        .merge(df_departments, how="left", on="department_id")
)

df_merged.head(10)

,order_id,product_id,add_to_cart_order,reordered,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,aisle,department
0,2,33120,1,1,202279,prior,3,5,9,8.0,Organic Egg Whites,86,16,eggs,dairy eggs
1,2,28985,2,1,202279,prior,3,5,9,8.0,Michigan Organic Kale,83,4,fresh vegetables,produce
2,2,9327,3,0,202279,prior,3,5,9,8.0,Garlic Powder,104,13,spices seasonings,pantry
3,2,45918,4,1,202279,prior,3,5,9,8.0,Coconut Butter,19,13,oils vinegars,pantry
4,2,30035,5,0,202279,prior,3,5,9,8.0,Natural Sweetener,17,13,baking ingredients,pantry
5,2,17794,6,1,202279,prior,3,5,9,8.0,Carrots,83,4,fresh vegetables,produce
6,2,40141,7,1,202279,prior,3,5,9,8.0,Original Unflavored Gelatine Mix,105,13,doughs gelatins bake mixes,pantry
7,2,1819,8,1,202279,prior,3,5,9,8.0,All Natural No Stir Creamy Almond Butter,88,13,spreads,pantry
8,2,43668,9,0,202279,prior,3,5,9,8.0,Classic Blend Cole Slaw,123,4,packaged vegetables fruits,produce
9,3,33754,1,1,205970,prior,16,5,17,12.0,Total 2% with Strawberry Lowfat Greek Strained...,120,16,yogurt,dairy eggs

In [8]:
# Save data as final
df_merged.to_parquet("../data/final.parquet", index=False)

In [9]:
# %pip install pyarrow